name: Feature request - NOT ACCEPTING NEW FEATURE REQUESTS
description: Feature requests are currently closed. The application is actively being rewritten https://github.com/audioling/audioling.
labels: ['enhancement']
body:
    - type: textarea
      attributes:
          label: What do you want to be added?
      validations:
          required: true
    - type: textarea
      attributes:
          label: Additional context
      validations:
          required: false
    - type: checkboxes
      attributes:
          label: Is this a server-specific feature? (e.g. Jellyfin only)
          options:
              - label: 'Yes'
                required: false
